name: oly

services:
  game_engine:
    build: .
    container_name: game.builder
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json

  core_engine:
    build:
      context: ./src/wasm
    container_name: engine.builder
    volumes:
      - ./src/wasm:/app
      - ./dist/wasm/:/app/build_wasm/
